version: '3.1'

services:

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gobs
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - go-network

volumes:
  postgres-data:
    driver: local

networks:
  go-network:
    driver: bridge